#!/usr/bin/env bash
cd $( dirname "${BASH_SOURCE[0]}")
{
	
	mvn jetty:run
}&


#java -Xdebug \
#	-Xrunjdwp:transport=dt_socket,address=5432,server=y,suspend=n \
#	-jar lp-content.jar > analysis.log 2>&1